-- haskell-tooling.hs
-- Haskell Development Tooling and Package Management
-- Practical guide to Haskell ecosystem tools

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE CPP #-}

module HaskellTooling where

import Control.Monad (when, unless)
import Data.List (intercalate, isPrefixOf)
import qualified Data.Map.Strict as Map
import qualified Data.Text as T
import qualified Data.Text.IO as TIO
import System.Directory
import System.Environment
import System.FilePath
import System.Process
import System.IO
import System.Exit

-- ============================================
-- 1. Cabal Package Configuration
-- ============================================

-- | Example .cabal file template
cabalTemplate :: String -> String -> String -> String -> String
cabalTemplate name version summary description = unlines $
    [ "cabal-version:       >=3.0"
    , "name:                " ++ name
    , "version:             " ++ version
    , "synopsis:           " ++ summary
    , "description:        " ++ description
    , "homepage:           https://github.com/username/" ++ name
    , "bug-reports:        https://github.com/username/" ++ name ++ "/issues"
    , "license:            MIT"
    , "license-file:       LICENSE"
    , "author:             Your Name"
    , "maintainer:         you@example.com"
    , "category:           Development"
    , "extra-source-files:"
    , "    CHANGELOG.md"
    , ""
    , "common common-options"
    , "    ghc-options:"
    , "        -Wall"
    , "        -Wcompat"
    , "        -Wincomplete-record-updates"
    , "        -Wincomplete-uni-patterns"
    , "        -Wredundant-constraints"
    , "        -Werror=incomplete-patterns"
    , "        -Wno-unsafe"
    , ""
    , "library"
    , "    import:           common-options"
    , "    hs-source-dirs:   src"
    , "    exposed-modules:"
    , "        " ++ name
    , "    build-depends:"
    , "        base >=4.15 && <5"
    , ""
    , "executable " ++ name ++ "-exe"
    , "    import:           common-options"
    , "    hs-source-dirs:   app"
    , "    main-is:          Main.hs"
    , "    build-depends:"
    , "        " ++ name ++ ","
    , "        base >=4.15 && <5"
    , ""
    , "test-suite " ++ name ++ "-test"
    , "    import:           common-options"
    , "    type:             exitcode-stdio-1.0"
    , "    hs-source-dirs:   test"
    , "    main-is:          Spec.hs"
    , "    build-depends:"
    , "        " ++ name ++ ","
    , "        base >=4.15 && <5,"
    , "        hspec >=2.0"
    , ""
    , "benchmark " ++ name ++ "-bench"
    , "    import:           common-options"
    , "    type:             exitcode-stdio-1.0"
    , "    hs-source-dirs:   bench"
    , "    main-is:          Bench.hs"
    , "    build-depends:"
    , "        " ++ name ++ ","
    , "        base >=4.15 && <5,"
    , "        criterion"
    ]

-- ============================================
-- 2. Stack Configuration
-- ============================================

-- | stack.yaml template
stackYamlTemplate :: String -> String
stackYamlTemplate resolver = unlines $
    [ "# This file was automatically generated by 'stack init'"
    , "# For more information, see: https://docs.haskellstack.org"
    , ""
    , "resolver: " ++ resolver
    , ""
    , "# User packages to be built"
    , "packages:"
    , "- ."
    , ""
    , "# Extra package databases containing global packages"
    , "extra-package-dbs: []"
    , ""
    , "# Override default flag values for local packages and extra-deps"
    , "flags: {}"
    , ""
    , "# Control what we do with unused extra-deps"
    , "extra-dep: true"
    , ""
    , "# Dependency packages to be pulled from upstream that are not in the resolver"
    , "# These entries can reference officially published versions as well as forks"
    , "# extra-deps: []"
    , ""
    , "# Override default flag values for local packages and extra-deps"
    , "# flags: {}"
    , ""
    , "# Extra package databases containing global packages"
    , "# extra-package-dbs: []"
    , ""
    , "# Control what we do with unused extra-deps"
    , "# unused-deps: warn"
    , ""
    , "# Whether to build with optimizations"
    , "# build:"
    , "#   optimized: false"
    , ""
    , "# Whether to use GHCi or the build system for REPL"
    , "# repl:"
    , "#   ghci-options:"
    , "#     - -fobject-code"
    , "#     - -fno-warn-type-defaults"
    , ""
    , "# Dependency packages to be pulled from upstream that are not in the resolver"
    , "# extra-deps:"
    , "# - acme-missiles-0.3"
    ]

-- ============================================
-- 3. Hspec Test Suite
-- ============================================

-- | Test specification template
hspecTemplate :: String -> String
hspecTemplate moduleName = unlines $
    [ "{-# LANGUAGE OverloadedStrings #-}"
    , "{-# LANGUAGE TypeApplications #-}"
    , ""
    , "module " ++ moduleName ++ "Spec where"
    , ""
    , "import Test.Hspec"
    , "import Test.Hspec.QuickCheck"
    , "import Test.QuickCheck"
    , "import " ++ moduleName
    , ""
    , "spec :: Spec"
    , "spec = do"
    , "    describe \"" ++ moduleName ++ "\" $ do"
    , "        it \"should have basic properties\" $ do"
    , "            1 + 1 `shouldBe` 2"
    , ""
    , "        prop \"should satisfy commutative property\" $ \\x y ->"
    , "            x + y == y + (x :: Int)"
    , ""
    , "    describe \"advanced functionality\" $ do"
    , "        it \"should handle edge cases\" $ do"
    , "            pendingWith \"Implement edge case tests\""
    , ""
    , "main :: IO ()"
    , "main = hspec spec"
    ]

-- ============================================
-- 4. Criterion Benchmark
-- ============================================

-- | Benchmark template
criterionTemplate :: String -> String
criterionTemplate moduleName = unlines $
    [ "{-# LANGUAGE BangPatterns #-}"
    , "import Criterion.Main"
    , "import " ++ moduleName
    , ""
    , "main :: IO ()"
    , "main = defaultMain"
    , "    [ bench \"sum list\" $ nf sumList [1..1000]"
    , "    , bench \"sum vector\" $ nf sumVector [1..1000]"
    , "    , bench \"map (*2) list\" $ nf (map (*2)) ([1..1000] :: [Int])"
    , "    , bench \"map (*2) vector\" $ nf (fmap (*2)) ([1..1000] :: [Int])"
    , "    ]"
    , ""
    , "sumList :: [Int] -> Int"
    , "sumList = foldl' (+) 0"
    , ""
    , "sumVector :: [Int] -> Int"
    , "sumVector = foldl' (+) 0"
    ]

-- ============================================
-- 5. Git Hooks and CI/CD
-- ============================================

-- | Pre-commit hook template
preCommitHook :: String
preCommitHook = unlines
    [ "#!/usr/bin/env bash"
    , ""
    , "# Haskell pre-commit hook"
    , "# Runs tests and linting before allowing commit"
    , ""
    , "set -e"
    , ""
    , "echo \"Running Haskell tests...\""
    , "stack test --fast"
    , ""
    , "echo \"Running HLint...\""
    , "if command -v hlint &> /dev/null; then"
    , "    hlint ."
    , "else"
    , "    echo \"HLint not found, skipping linting\""
    , "fi"
    , ""
    , "echo \"Running fourmolu formatting check...\""
    , "if command -v fourmolu &> /dev/null; then"
    , "    fourmolu --mode check ."
    , "else"
    , "    echo \"Fourmolu not found, skipping formatting check\""
    , "fi"
    , ""
    , "echo \"All checks passed!\""
    ]

-- | GitHub Actions CI workflow
githubActionsTemplate :: String
githubActionsTemplate = unlines
    [ "name: Haskell CI"
    , ""
    , "on:"
    , "  push:"
    , "    branches: [ main ]"
    , "  pull_request:"
    , "    branches: [ main ]"
    , ""
    , "jobs:"
    , "  build:"
    , "    runs-on: ubuntu-latest"
    , ""
    , "    steps:"
    , "    - uses: actions/checkout@v3"
    , ""
    , "    - name: Setup Haskell"
    , "      uses: haskell-actions/setup@v2"
    , "      with:"
    , "        ghc-version: '9.6'"
    , "        cabal-version: 'latest'"
    , ""
    , "    - name: Cache dependencies"
    , "      uses: actions/cache@v3"
    , "      with:"
    , "        path: |"
    , "          ~/.cabal/packages"
    , "          ~/.cabal/store"
    , "          dist-newstyle"
    , "        key: ${{ runner.os }}-${{ hashFiles('*.cabal', 'cabal.project', 'cabal.project.local') }}"
    , ""
    , "    - name: Install dependencies"
    , "      run: cabal update && cabal build --only-dependencies"
    , ""
    , "    - name: Build"
    , "      run: cabal build all"
    , ""
    , "    - name: Run tests"
    , "      run: cabal test"
    , ""
    , "    - name: Run benchmarks"
    , "      run: cabal bench"
    ]

-- ============================================
-- 6. Docker Configuration
-- ============================================

-- | Dockerfile for Haskell projects
dockerfileTemplate :: String
dockerfileTemplate = unlines
    [ "FROM haskell:9.6-slim AS builder"
    , ""
    , "WORKDIR /app"
    , ""
    , "COPY . ."
    , ""
    , "RUN apt-get update && apt-get install -y \\"
    , "    git \\"
    , "    && rm -rf /var/lib/apt/lists/*"
    , ""
    , "RUN cabal update"
    , "RUN cabal build --enable-executable-dynamic"
    , ""
    , "FROM debian:bookworm-slim"
    , ""
    , "WORKDIR /app"
    , ""
    , "RUN apt-get update && apt-get install -y \\"
    , "    libgmp-dev \\"
    , "    && rm -rf /var/lib/apt/lists/*"
    , ""
    , "COPY --from=builder /app/dist-newstyle/build/*/*/*/app/build/*/app /app/"
    , ""
    , "CMD [\"/app/app\"]"
    ]

-- ============================================
-- 7. Development Scripts
-- ============================================

-- | Development environment setup script
setupScript :: String
setupScript = unlines
    [ "#!/usr/bin/env bash"
    , ""
    , "# Haskell development environment setup"
    , ""
    , "set -e"
    , ""
    , "echo \"Installing GHC and Cabal...\""
    , "if ! command -v ghcup &> /dev/null; then"
    , "    curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh"
    , "fi"
    , ""
    , "# Update PATH"
    , 'export PATH="$HOME/.ghcup/bin:$PATH"'
    , ""
    , "echo \"Installing GHC...\""
    , "ghcup install ghc 9.6.4"
    , "ghcup set ghc 9.6.4"
    , ""
    , "echo \"Installing Cabal...\""
    , "ghcup install cabal 3.10"
    , "ghcup set cabal 3.10"
    , ""
    , "echo \"Installing HLS...\""
    , "ghcup install hls"
    , ""
    , "echo \"Installing useful tools...\""
    , "cabal install \\"
    , "    fourmolu \\"
    , "    hlint \\"
    , "    hasktags \\"
    , "    hoogle"
    , ""
    , "echo \"Generating Hoogle database...\""
    , "hoogle generate"
    , ""
    , "echo \"Development environment setup complete!\""
    ]

-- | Build and run script
buildScript :: String
buildScript = unlines
    [ "#!/usr/bin/env bash"
    , ""
    , "# Build and run Haskell project"
    , ""
    , "set -e"
    , ""
    , "echo \"Cleaning...\""
    , "cabal clean"
    , ""
    , "echo \"Building...\""
    , "cabal build"
    , ""
    , "echo \"Running tests...\""
    , "cabal test"
    , ""
    , "echo \"Running benchmarks...\""
    , "cabal bench"
    , ""
    , "echo \"Running application...\""
    , "cabal run"
    ]

-- ============================================
-- 8. Editor Configuration
-- ============================================

-- | VSCode Haskell configuration
vscodeSettings :: String
vscodeSettings = unlines
    [ "{"
    , "    \"haskell.serverExecutablePath\": \"haskell-language-server-wrapper\","
    , "    \"haskell.formattingProvider\": \"fourmolu\","
    , "    \"haskell.manageHLS\": \"GHCup\","
    , "    \"haskell.trace.server\": \"messages\","
    , "    \"files.associations\": {"
    , "        \"*.hs\": \"haskell\""
    , "    },"
    , "    \"editor.formatOnSave\": true,"
    , "    \"[haskell]\": {"
    , "        \"editor.defaultFormatter\": \"taylor.faust.haskell-fourmolu\","
    , "        \"editor.formatOnSave\": true"
    , "    },"
    , "    \"files.exclude\": {"
    , "        \"**/.stack-work\": true,"
    , "        \"**/dist-newstyle\": true,"
    , "        \"**/.ghc.environment.*\": true"
    , "    }"
    , "}"
    ]

-- | Fourmolu configuration
fourmoluConfig :: String
fourmoluConfig = unlines
    [ "indentation: 4"
    , "comma-style: leading"
    , "import-export-style: diff-friendly"
    , "record-brace-space: false"
    , "indent-wheres: true"
    , "function-arrows: trailing"
    , "haddock-style: multi-line"
    , "newlines-between-decls: 1"
    , "pretty-case: true"
    , "respectful: true"
    , "fixities: []"
    , "import-export-style: diff-friendly"
    , "import-export-grouping: by-type"
    ]

-- ============================================
-- 9. Documentation Generation
-- ============================================

-- | Haddock documentation example
haddockExample :: String
haddockExample = unlines
    [ "-- | Module for demonstrating Haddock documentation"
    , "--"
    , "-- This module shows how to write good documentation"
    , "-- for Haskell libraries using Haddock."
    , "--"
    , "-- Example usage:"
    , "--"
    , "-- >>> add 1 2"
    , "-- 3"
    , "--"
    , moduleName
    , "module DocumentationExample where"
    , ""
    , "-- | Add two numbers together."
    , "--"
    , "-- This function performs addition of two integers."
    , "--"
    , "-- Examples:"
    , "--"
    , "-- >>> add 1 2"
    , "-- 3"
    , "--"
    , "-- >>> add (-1) 1"
    , "-- 0"
    , "--"
    , "-- prop> \\x y -> add x y == add y x"
    , "-- prop> \\x y z -> add x (add y z) == add (add x y) z"
    , "add :: Int -> Int -> Int"
    , "add x y = x + y"
    , ""
    , "-- | Safe division that returns 'Nothing' on division by zero."
    , "--"
    , "-- >>> safeDiv 10 2"
    , "-- Just 5"
    , "--"
    , "-- >>> safeDiv 10 0"
    , "-- Nothing"
    , "safeDiv :: Int -> Int -> Maybe Int"
    , "safeDiv _ 0 = Nothing"
    , "safeDiv x y = Just (x `div` y)"
    , ""
    , "-- $setup"
    , "-- >>> import Test.QuickCheck"
    , "--"
    , "-- QuickCheck properties:"
    , "--"
    , "-- prop> \\x y -> add x y == x + y"
    ]
  where
    moduleName = "module DocumentationExample where"

-- ============================================
-- 10. Dependency Management
-- ============================================

-- | Package version constraints example
dependencyManagement :: String
dependencyManagement = unlines
    [ "-- Common dependency patterns"
    , ""
    , "-- Exact version"
    , "-- build-depends: aeson ==1.5.6.0"
    , ""
    , "-- Version range"
    , "-- build-depends: aeson >=1.5 && <1.6"
    , ""
    , "-- Major version bounds"
    , "-- build-depends: aeson ^>=1.5"
    , ""
    , "-- Multiple packages"
    , "-- build-depends:"
    , "--     base >=4.15 && <5,"
    , "--     aeson >=1.5 && <1.6,"
    , "--     bytestring >=0.10 && <0.12,"
    , "--     text >=1.2 && <2.1,"
    , "--     vector >=0.12 && <0.14"
    , ""
    , "-- Conditional dependencies"
    , "-- if flag(network)"
    , "--   build-depends: network >=3.0 && <3.2"
    , "-- else"
    , "--   build-depends: network-bsd >=2.8 && <2.9"
    , ""
    , "-- Test dependencies"
    , "-- test-depends:"
    , "--     hspec >=2.0,"
    , "--     QuickCheck >=2.14"
    , ""
    , "-- Benchmark dependencies"
    , "-- benchmark-depends:"
    , "--     criterion >=1.5"
    ]

-- ============================================
-- 11. Common Project Structure
-- ============================================

projectStructure :: IO ()
projectStructure = do
    putStrLn "Typical Haskell project structure:"
    putStrLn ""
    putStrLn "├── app/"
    putStrLn "│   └── Main.hs                 # Executable entry point"
    putStrLn "├── src/"
    putStrLn "│   └── MyLibrary/"
    putStrLn "│       ├── Internal/"
    putStrLn "│       │   └── Utils.hs        # Internal utilities"
    putStrLn "│       └── MyLibrary.hs        # Library module"
    putStrLn "├── test/"
    putStrLn "│   └── Spec.hs                 # Test suite"
    putStrLn "├── bench/"
    putStrLn "│   └── Bench.hs                # Benchmarks"
    putStrLn "├── ChangeLog.md                 # Changelog"
    putStrLn "├── LICENSE                      # License file"
    putStrLn "├── README.md                    # Project documentation"
    putStrLn "├── Setup.hs                     # Cabal setup script"
    putStrLn "├── package.yaml                 # Stack package file"
    putStrLn "├── stack.yaml                   # Stack configuration"
    putStrLn "├── cabal.project                 # Cabal project file"
    putStrLn "├── .gitignore                   # Git ignore patterns"
    putStrLn "├── .hlint.yaml                  # HLint configuration"
    putStrLn "├── .editorconfig                 # Editor configuration"
    putStrLn "└── .github/"
    putStrLn "    └── workflows/"
    putStrLn "        └── ci.yml               # GitHub Actions workflow"

-- ============================================
-- 12. Tool Commands Reference
-- ============================================

toolCommands :: IO ()
toolCommands = do
    putStrLn "Essential Haskell tooling commands:"
    putStrLn ""
    putStrLn "Build and Run:"
    putStrLn "  cabal build                    # Build project"
    putStrLn "  cabal run                      # Run executable"
    putStrLn "  cabal test                     # Run tests"
    putStrLn "  cabal bench                    # Run benchmarks"
    putStrLn "  cabal repl                     # Start REPL"
    putStrLn ""
    putStrLn "  stack build                    # Build with Stack"
    putStrLn "  stack exec my-app              # Run with Stack"
    putStrLn "  stack test                     # Test with Stack"
    putStrLn "  stack ghci                     # REPL with Stack"
    putStrLn ""
    putStrLn "Development:"
    putStrLn "  ghci                           # GHC interactive"
    putStrLn "  ghc --make                     # Compile directly"
    putStrLn "  runghc                         # Run script"
    putStrLn "  hlint                          # Lint code"
    putStrLn "  fourmolu                       # Format code"
    putStrLn "  hoogle search                  # Search documentation"
    putStrLn "  haddock                        # Generate docs"
    putStrLn ""
    putStrLn "Package Management:"
    putStrLn "  cabal update                   # Update package list"
    putStrLn "  cabal install                   # Install package"
    putStrLn "  cabal list                      # List packages"
    putStrLn "  stack update                    # Update Stack"
    putStrLn "  stack install                   # Install with Stack"
    putStrLn ""
    putStrLn "Project Creation:"
    putStrLn "  cabal init                     # Initialize Cabal project"
    putStrLn "  stack new                      # Create Stack project"
    putStrLn "  ghcup tui                      # Manage Haskell tools"

-- ============================================
-- Main Function
-- ============================================

main :: IO ()
main = do
    putStrLn "Haskell Development Tooling Guide"
    putStrLn "=================================="
    putStrLn ""
    
    putStrLn "1. Cabal Configuration:"
    putStrLn $ cabalTemplate "my-package" "0.1.0.0" "My awesome package" "Long description"
    
    putStrLn "\n2. Stack Configuration:"
    putStrLn $ stackYamlTemplate "lts-21.0"
    
    putStrLn "\n3. Test Suite Template:"
    putStrLn $ hspecTemplate "MyModule"
    
    putStrLn "\n4. Benchmark Template:"
    putStrLn $ criterionTemplate "MyModule"
    
    putStrLn "\n5. Common Project Structure:"
    projectStructure
    
    putStrLn "\n6. Tool Commands Reference:"
    toolCommands
    
    putStrLn "\n7. Documentation Example:"
    putStrLn haddockExample
    
    putStrLn "\n8. Dependency Management:"
    putStrLn dependencyManagement
    
    putStrLn "\nTooling examples generated successfully!"
    putStrLn "\nRemember to:"
    putStrLn "1. Set up proper .gitignore for Haskell projects"
    putStrLn "2. Configure your editor with Haskell Language Server"
    putStrLn "3. Set up CI/CD pipelines"
    putStrLn "4. Write comprehensive documentation"
    putStrLn "5. Maintain version bounds in .cabal files"